language: python
python:
  - "3.6"

env:
  global:
    - REGISTRY_URL=registry.heroku.com
    - IMAGE_NAME="${REGISTRY_URL}/extreme-crypto-investor/web"
    - HEROKU_APP=extreme-crypto-investor

stages:
  - test
  - name: untagged
    if: branch !=  master
  - name: latest
    if: branch = master

cache:
  pip: true

jobs:
  include:
    - stage: test
      install:
        - make install
      script:
        - make lint
        - make test
    - stage: untagged
      if: type = push
      env:
        - IMAGE_TAG: ${TRAVIS_JOB_ID}
      services:
        - docker
      script:
        - make sdist
        - docker build --no-cache -t "${IMAGE_NAME}:${IMAGE_TAG}" .
    - stage: latest
      if: NOT type = pull_request
      env:
        - IMAGE_TAG: latest
      services:
        - docker
      script:
        - make sdist
        - docker build --no-cache -t "${IMAGE_NAME}:${IMAGE_TAG}" .
      after_script:
        - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" ${REGISTRY_URL}
        - docker push "${IMAGE_NAME}:${IMAGE_TAG}"
      branches:
        only:
        - master
