language: python
python:
  - "3.6"

stages:
  - install
  - test
  - build
  - name: deploy
    if: branch = master

cache:
  pip: true

jobs:
  include:
    - stage: install
      script:
        - make install
    - stage: test
      before_script:
        - pip install -r requirements/test.txt
      script:
        - make lint
        - make test
    - stage: build
      services:
        - docker
      script:
        - make sdist
        - docker build . -t crypto-investor
    - stage: deploy
      script: []
