#!/bin/sh

rm -f /run/nginx/nginx.conf
rm -f /usr/local/nginx/logs/nginx.pid
mkdir -p /var/tmp/nginx

cat > /etc/nginx/conf.d/cryptoinvestor.conf <<EOF
upstream app_server {
    server unix:/tmp/nginx.socket fail_timeout=0;
}

server {
    location /public/ {
        autoindex on;
        alias /public/;
    }

    location / {
        proxy_redirect off;
        proxy_pass http://app_server;
    }

    listen ${PORT};
    server_name _;
    keepalive_timeout 5;
}
EOF

if [ "$#" -eq 0 ]; then
    exec runsvdir /etc/service
fi

exec "$@"
